import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { outfit } from "./fonts";
import { initializeFapiStorage } from "@/utils/functions/initializeFapiStorage.util";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FAPI - Fake APIs on the fly",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const port = process.env.PORT || "3000";
  await initializeFapiStorage(port);
  return (
    <html lang="en" className={outfit.variable}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
