import { initializeApp } from "@/utils/functions/initializeApp";
import RootLayoutClient from "./rootLayoutClient";
import type { Metadata } from "next";
import StoreProvider from "./storeProvider";

export const metadata: Metadata = {
  title: "FAPI - Fake APIs on the fly",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  /* Server-side initialization */
  await initializeApp();

  /* Pass children to client component */
  return (
    <StoreProvider>
      <RootLayoutClient>{children}</RootLayoutClient>
    </StoreProvider>
  );
}
